apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: client
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orange
spec:
  rules:
    - host: orange-stg.yhmd.dev
      http:
        paths:
          - path: /game.v1.GameService/
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 80
